#!/bin/sh
# Copyright 2026 Josh Waldrep
# SPDX-License-Identifier: Apache-2.0
#
# Pipelock playground per-visitor microVM boot entrypoint (Fly.io / Firecracker).
#
# The microVM is the filesystem + visitor-vs-visitor isolation boundary (clean
# image, destroyed per session). This entrypoint adds the EGRESS boundary that
# the microVM does NOT provide for free: it loads the proven kernel owner-match
# rule so the contained agent uid can reach ONLY the in-process Pipelock proxy,
# then PROVES the drop and aborts the VM if it cannot (fail-closed). Pipelock
# stays the egress firewall inside the VM; this rule stops the agent skipping it.
#
# Fail-closed: any step failing exits non-zero, so the machine never serves an
# agent it could not contain. The nft rule is generated by the SHIPPED renderer
# (`print-containment-nft`), never a hand-copied rule, so it cannot drift.
set -eu

AGENT_USER="${PLAYGROUND_AGENT_USER:-pipelock-agent}"
AGENT_UID="${PLAYGROUND_AGENT_UID:-10001}"
PROXY_PORT="${PLAYGROUND_PROXY_PORT:-8888}"
LISTEN="${PLAYGROUND_LISTEN:-0.0.0.0:8080}"
BIN=/usr/local/bin/pipelock-playground-live
TOYAGENT_BIN=/usr/local/bin/pipelock-playground-toyagent
WEBTOOL_BIN=/usr/local/bin/pipelock-playground-webtool
LLM_AGENT_BIN=/usr/local/bin/pipelock-playground-llm-agent

log() { printf '[entrypoint] %s\n' "$*" >&2; }

# --- Secrets: env -> tmpfs file, kept out of argv -------------------------------
# Fly delivers secrets as env vars; the server wants file paths so the values
# never land in argv / process listing. Write them 0600 under /run (tmpfs).
SECRET_DIR=/run/playground
mkdir -p "${SECRET_DIR}"
chmod 0700 "${SECRET_DIR}"

ORCH_KEY_ARGS=""
if [ -n "${PLAYGROUND_ORCHESTRATOR_KEY:-}" ]; then
	umask 077
	printf '%s' "${PLAYGROUND_ORCHESTRATOR_KEY}" >"${SECRET_DIR}/orchestrator.key"
	ORCH_KEY_ARGS="--orchestrator-key ${SECRET_DIR}/orchestrator.key"
fi

MODEL_KEY_ARGS=""
if [ -n "${PLAYGROUND_MODEL_KEY:-}" ]; then
	umask 077
	printf '%s' "${PLAYGROUND_MODEL_KEY}" >"${SECRET_DIR}/model.key"
	MODEL_KEY_ARGS="--model-secret-file ${SECRET_DIR}/model.key"
fi

# --- 1. Load the proven owner-match egress rule (shipped renderer) --------------
log "loading containment nft rule (agent uid ${AGENT_UID} -> only 127.0.0.1:${PROXY_PORT})"
"${BIN}" print-containment-nft --agent-uid "${AGENT_UID}" --proxy-port "${PROXY_PORT}" | nft -f -

# --- 2. Prove the drop is live BEFORE serving (fail-closed boot gate) ------------
log "proving containment (aborts the VM if the agent uid can still egress)"
"${BIN}" verify-containment --toyagent-bin "${TOYAGENT_BIN}" --agent-user "${AGENT_USER}"

# --- 3. Serve. Per-session/model flags come from the broker via "$@". -----------
log "containment proven; starting server on ${LISTEN}"
# shellcheck disable=SC2086  # word-splitting of the optional key args is intended
exec "${BIN}" serve \
	--self-managed-containment \
	--listen "${LISTEN}" \
	--proxy-port "${PROXY_PORT}" \
	--toyagent-bin "${TOYAGENT_BIN}" \
	--webtool-bin "${WEBTOOL_BIN}" \
	--llm-agent-bin "${LLM_AGENT_BIN}" \
	${ORCH_KEY_ARGS} \
	${MODEL_KEY_ARGS} \
	"$@"
